# fly.toml app configuration file generated for api-artikel on 2024-01-22T21:34:08+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "api-artikel"
primary_region = "sin"

[build]

[env]
  DATABASE_ENVIRONMENT = "production"
  PORT = "8080"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
